### ISSUE TITLE
OpenSSL::ASN1::ASN1Error : illegal padding on HPE devices

### ISSUE THREAD

**Issue by fwininger** [HoneyryderChuck/ruby-netsnmp#5]
I have an exception on a HP 1910 device

Exception : 

```
OpenSSL::ASN1::ASN1Error : illegal padding
```

Device detail : 

```
HP V1910-24G Switch Software Version 5.20, Release 1513P62
```

stack trace :
```
ruby-netsnmp-42a77f576e78/lib/netsnmp/security_parameters.rb:120:in `decode'
ruby-netsnmp-42a77f576e78/lib/netsnmp/security_parameters.rb:120:in `decode'
ruby-netsnmp-42a77f576e78/lib/netsnmp/message.rb:64:in `decode'
ruby-netsnmp-42a77f576e78/lib/netsnmp/v3_session.rb:81:in `decode'
ruby-netsnmp-42a77f576e78/lib/netsnmp/v3_session.rb:27:in `send'
ruby-netsnmp-42a77f576e78/lib/netsnmp/client.rb:69:in `block in get_next'
ruby-netsnmp-42a77f576e78/lib/netsnmp/client.rb:157:in `handle_retries'
ruby-netsnmp-42a77f576e78/lib/netsnmp/client.rb:69:in `get_next'
ruby-netsnmp-42a77f576e78/lib/netsnmp/client.rb:88:in `block (3 levels) in walk'
ruby-netsnmp-42a77f576e78/lib/netsnmp/client.rb:87:in `loop'
ruby-netsnmp-42a77f576e78/lib/netsnmp/client.rb:87:in `block (2 levels) in walk'
ruby-netsnmp-42a77f576e78/lib/netsnmp/client.rb:86:in `catch'
ruby-netsnmp-42a77f576e78/lib/netsnmp/client.rb:86:in `block in walk'
```

**Comment by HoneyryderChuck** [comment]
Thx for the report.

Can you isolate the call into a reproducible script? I need to see what's wrong with the encrypted string, in order to provide a workaround.

**Comment by Xeitor** [comment]
Hi @HoneyryderChuck, so glad you took the time to answer, this is a work related issue an my team and I are a little bit lost

Here are the details:

## Versions
```
ruby: 3.3.0
openssl: 3.2.0
netsnmp: 0.7.1
snmp: depends on the device
```

## Device
```
type: Optical Line Terminal
brand: Huawei
model: MA5680T
```

## Payload debug
### client
```
irb(main):079> credentials = {:host=>"", :port=>, :community=>"", :version=>:v2c, :timeout=>5, :retries=>2, :debug=>nil, :debug_level=>0}
irb(main):080> client = NETSNMP::Client.new(**credentials)
=>
#<NETSNMP::Client:0x00007d97f1797578
...
irb(main):081> client
=>
#<NETSNMP::Client:0x00007d97f1797578
 @retries=2,
 @session=
  #<NETSNMP::Session:0x00007d97f2defd20
   @community="W1spr0c0mmun17!",
   @debug=nil,
   @debug_level=0,
   @transport=
    #<NETSNMP::Session::Transport:0x00007d97f1797528 @destaddr="\x02\x00\bq-G\xCB\x15\x00\x00\x00\x00\x00\x00\x00\x00", @socket=#<UDPSocket:fd 16, AF_INET, 0.0.0.0, 0>, @timeout=5>,
   @version=1>>
```
### execution with debug enabled
```
irb(main):035> client.get(oid: '1.3.6.1.4.1.2011.6.128.1.1.2.45.1.2.4194312192.18')

sending request...

3040 0201 0104 0f57 3173 7072 3063 306d
6d75 6e31 3721 a02a 0204 37cc 3b25 0201
0002 0100 301c 301a 0616 2b06 0104 018f
5b06 8100 0101 022d 0102 8fd0 80c0 0012
0500

received response

3044 0201 0104 0f57 3173 7072 3063 306d
6d75 6e31 3721 a22e 0204 37cc 3b25 0201
0002 0100 3020 301e 0616 2b06 0104 018f
5b06 8100 0101 022d 0102 8fd0 80c0 0012
0204 ffff ffff
(irb):35:in `<main>': illegal padding (OpenSSL::ASN1::ASN1Error)
```

### using linux snmp
```

╰─ snmpget -v2c -c <community> <host> 1.3.6.1.4.1.2011.6.128.1.1.2.45.1.2.4194312192.18
                                                                                                                                                                                             
iso.3.6.1.4.1.2011.6.128.1.1.2.45.1.2.4194312192.18 = INTEGER: -1

```

**Comment by pgorgita** [comment]
This pure Ruby ASN1 gem seems quite good and is gaining traction. [RASN1](https://github.com/lemontree55/rasn1)

**Comment by HoneyryderChuck** [comment]
👋 `rasn1` does not seem to chew this either:

```ruby
require "rasn1"
RASN1.parse("0D\u0002\u0001\u0001\u0004\u000FW1spr0c0mmun17!\xA2.\u0002\u0004%\xD9\xD4\xDE\u0002\u0001\u0000\u0002\u0001\u00000 0\u001E\u0006\u0016+\u0006\u0001\u0004\u0001\x8F[\u0006\x81\u0000\u0001\u0001\u0002-\u0001\u0002\x8FЀ\xC0\u0000\u0012\u0002\u0004\xFF\xFF\xFF\xFF") #=> :in 'RASN1::Types::Base#raise_id_error': Expected CONTEXT CONSTRUCTED BASE but get CONTEXT CONSTRUCTED INTEGER (RASN1::ASN1Error) ...

# it also fails to parse the unpadded bytes, same error....
```

**Comment by Xeitor** [comment]
massive thanks @HoneyryderChuck for taking the time to answer 

I made some tests my self with rasn1 and while it successfully parsed the one that open SSL gives the padding error, it failed to parse other responses openssl can parse

so I don't know, I'll submit a ticket to openssl and see I someone can help me out

in the meantime I think we will try a python library that seems to work pretty god

**Comment by pgorgita** [comment]
> 👋 `rasn1` does not seem to chew this either:
> 
> require "rasn1"
> RASN1.parse("0D\u0002\u0001\u0001\u0004\u000FW1spr0c0mmun17!\xA2.\u0002\u0004%\xD9\xD4\xDE\u0002\u0001\u0000\u0002\u0001\u00000 0\u001E\u0006\u0016+\u0006\u0001\u0004\u0001\x8F[\u0006\x81\u0000\u0001\u0001\u0002-\u0001\u0002\x8FЀ\xC0\u0000\u0012\u0002\u0004\xFF\xFF\xFF\xFF") #=> :in 'RASN1::Types::Base#raise_id_error': Expected CONTEXT CONSTRUCTED BASE but get CONTEXT CONSTRUCTED INTEGER (RASN1::ASN1Error) ...
> 
> # it also fails to parse the unpadded bytes, same error....


@HoneyryderChuck  - I think that the issue there is ANSI related.

I believe the pdu_der you have above might be correctly coded to HEX String using [Array#pack ](https://ruby-doc.org/core-3.0.1/Array.html#method-i-pack)

```ruby
pdu_der = ["3044020101040f57317370723063306d6d756e313721a22e020425d9d4de0201000201003020301e06162b060104018f5b0681000101022d01028fd080c000120204ffffffff"].pack('H*')
=> "0D\x02\x01\x01\x04\x0FW1spr0c0mmun17!\xA2.\x02\x04%\xD9\xD4\xDE\x02\x01\x00\x02\x01\x000 0\x1E\x06\x16+\x06\x01\x04\x01\x8F[\x06\x81\x00\x01\x01\x02-\x01\x02\x8F\xD0\x80\xC0\x00\x12\x02\x04\xFF\xFF\xFF\xFF"

RASN1.parse(pdu_der)
=> SEQUENCE:
  INTEGER: 1
  OCTET STRING: "W1spr0c0mmun17!"
  CONTEXT BASE: [INTEGER: 635032798, INTEGER: 0, INTEGER: 0, SEQUENCE:
  SEQUENCE:
    OBJECT ID: "1.3.6.1.4.1.2011.6.128.1.1.2.45.1.2.4194312192.18"
    INTEGER: -1

]
```

_note - I am using RASN1 master at commit [#eebdc49 ](https://github.com/lemontree55/rasn1/commit/eebdc49657c19551b6514d7010bdd23d45ba0769) - includes fix to issue reported and solved in 1 day!_
