### ISSUE TITLE
Getting Error "NameError - uninitialized constant Socket::MSG_DONTWAIT Did you mean? Socket::MSG_DONTROUTE"

### ISSUE THREAD

**Issue by namanjain851** [HoneyryderChuck/ruby-netsnmp#6]
Getting error while running get method for snmp v3 credential 

```ruby
"netsnmp/session.rb:94:in `block in write': uninitialized constant Socket::MSG_DONTWAIT (NameError)

        @socket.sendmsg(payload, Socket::MSG_DONTWAIT, @destaddr)
                                        ^^^^^^^^^^^^^^
Did you mean? Socket::MSG_DONTROUTE
     from C:/lib/netsnmp/session.rb:110:in `block in perform_io'
     from C:/ib/netsnmp/session.rb:108:in `loop'
     from C:/lib/netsnmp/session.rb:108:in `perform_io'
     from C:/lib/netsnmp/session.rb:93:in `write'
     from C:/lib/netsnmp/session.rb:88:in `send'
     from C:/lib/netsnmp/session.rb:53:in `send'
     from C:/lib/netsnmp/client.rb:57:in `block in get'
     from C:/lib/netsnmp/client.rb:157:in `handle_retries'
     from C:/lib/netsnmp/client.rb:57:in `get'"
     
     Version used for netsnmp : 0.7.1
     System Specification : Windows Server 2019 Datacentre

**Comment by HoneyryderChuck** [comment]
fixed with 83c3f3a1a3db976ae213638052ab71b87a89125e
